### ISSUE TITLE
Prepare for Your Project Game

### ISSUE THREAD

**Issue by nesterone** [brotherhood-of-javascript/js-eng-init#139]

**Comment by yzhbankov** [comment]
1. Creation of graphical shell (8 elephants)
-field
-dimensions choosing
-time counter
-mines counter

2. Make the field splitting on the number of selected elements (5 elephants)

3. Make the coordinate handler (3 elephants)

4. Generation and recording mines algorithm (5 elephants)

5. Algorithm of opening the empty cells (8 elephants)

6. Algorithm of exploding (3 elephants)

7. Graphical realization of cells opening (8 elephants)

**Comment by nesterone** [comment]
Better to start with #2 but
include simple table with opening cells and simple mine generator

**Comment by yzhbankov** [comment]
1. Make the field splitting on the number of selected elements.
- menu of field size determination;
- changing the field size;
- highlighting the cells under mouse pointer.

2. Create the algorithm of mines generation
- the mines counter

3. Create the algorithm of cells opening 
- graphical realization;
- the time counter;
- exploding algorithm;
- empty cells opening algorithm;
